<?php
/**
 * B2W Digital - Companhia Digital
 *
 * Do not edit this file if you want to update this SDK for future new versions.
 * For support please contact the e-mail bellow:
 *
 * sdk@e-smart.com.br
 *
 * @category  SkuHub
 * @package   SkuHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br).
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

namespace IntegraCommerce\Api\EntityInterface\Catalog;

use IntegraCommerce\Api\EntityInterface\Catalog\Product\MutualMethods;
use IntegraCommerce\Api\EntityInterface\Catalog\Product\Variation;
use IntegraCommerce\Api\EntityInterface\EntityAbstract;

class Category extends EntityAbstract
{

    /**
     * @param string $code
     *
     * @return $this
     */
    // public function setCode($code)
    // {
    //     $this->setData('code', (string) $code);
    //     return $this;
    // }

    public function setCode($code)
    {
        $this->setData('Id', (string) $code);
        return $this;
    }


    /**
     * @param string $name
     *
     * @return $this
     */
    // public function setName($name)
    // {
    //     $this->setData('name', (string) $name);
    //     return $this;
    // }

    public function setName($name)
    {
        $this->setData('Name', (string) $name);
        return $this;
    }

    public function setParentCode($parent_code)
    {
        $this->setData('ParentId', (string) $parent_code);
        return $this;
    }


    /**
     * @return string
     */
    // public function getCode()
    // {
    //     return (string) $this->getData('code');
    // }

    public function getCode()
    {
        return (string) $this->getData('Id');
    }


    /**
     * @return string
     */
    // public function getName()
    // {
    //     return (string) $this->getData('name');
    // }

    public function getName()
    {
        return (string) $this->getData('Name');
    }

    public function getParentCode()
    {
        return (string) $this->getData('ParentId');
    }


    /**
     * @return array
     */
    public function export()
    {
        return [
            'category' => (array) $this->getData()
        ];
    }


    /**
     * @return \IntegraCommerce\Api\Handler\Response\HandlerInterface
     */
    public function create()
    {
        $this->validate();

        /** @var \IntegraCommerce\Api\Handler\Request\Catalog\CategoryHandler $handler */
        $handler = $this->requestHandler();

        /** @var \IntegraCommerce\Api\Handler\Response\HandlerInterface $response */
        $response = $handler->create($this->getCode(), $this->getName(),$this->getParentCode());

        return $response;
    }


    /**
     * @return \IntegraCommerce\Api\Handler\Response\HandlerInterface
     */
    public function update()
    {
        $this->validate();

        /** @var \IntegraCommerce\Api\Handler\Request\Catalog\CategoryHandler $handler */
        $handler = $this->requestHandler();

        /** @var \IntegraCommerce\Api\Handler\Response\HandlerInterface $response */
        $response = $handler->create($this->getCode(), $this->getName(),$this->getParentCode());

        return $response;
    }


    /**
     * @return \IntegraCommerce\Api\Handler\Response\HandlerInterface
     */
    public function delete()
    {
        /** @var \IntegraCommerce\Api\Handler\Request\Catalog\CategoryHandler $handler */
        $handler = $this->requestHandler();

        /** @var \IntegraCommerce\Api\Handler\Response\HandlerInterface $response */
        $response = $handler->delete($this->getCode());

        return $response;
    }


    /**
     * @return \IntegraCommerce\Api\Handler\Response\HandlerInterface
     */
    public function categories()
    {
        /** @var \IntegraCommerce\Api\Handler\Request\Catalog\CategoryHandler $handler */
        $handler = $this->requestHandler();
        return $handler->categories();
    }
}
