<?php
/**
 * B2W Digital - Companhia Digital
 *
 * Do not edit this file if you want to update this SDK for future new versions.
 * For support please contact the e-mail bellow:
 *
 * sdk@e-smart.com.br
 *
 * @category  SkuHub
 * @package   SkuHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br).
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

namespace IntegraCommerce\Api\Handler\Request\Sales\Order;

use IntegraCommerce\Api\EntityInterface\Sales\Order\Queue;
use IntegraCommerce\Api\Handler\Request\HandlerAbstract;

class QueueHandler extends HandlerAbstract
{

    /** @var string */
    protected $baseUrlPath = '/queues';


    /**
     * Retrieves and first order available in the queue in IntegraCommerce.
     *
     * @return \IntegraCommerce\Api\Handler\Response\HandlerInterface
     */
    public function orders()
    {
        /** @var \IntegraCommerce\Api\Handler\Response\HandlerInterface $responseHandler */
        $responseHandler = $this->service()->get($this->baseUrlPath('orders'));
        return $responseHandler;
    }


    /**
     * Removes an order from the integration queue.
     *
     * @param string $orderId
     *
     * @return \IntegraCommerce\Api\Handler\Response\HandlerInterface
     */
    public function delete($orderId)
    {
        /** @var \IntegraCommerce\Api\Handler\Response\HandlerInterface $responseHandler */
        $responseHandler = $this->service()->delete($this->baseUrlPath("orders/{$orderId}"));
        return $responseHandler;
    }


    /**
     * @return Queue
     */
    public function entityInterface()
    {
        return new Queue($this);
    }
}
