<?php
/**
 * B2W Digital - Companhia Digital
 *
 * Do not edit this file if you want to update this SDK for future new versions.
 * For support please contact the e-mail bellow:
 *
 * sdk@e-smart.com.br
 *
 * @category  SkuHub
 * @package   SkuHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br).
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

namespace IntegraCommerce\Api\Log\TypeInterface;

use IntegraCommerce\Api\Handler\Response\HandlerInterfaceException;
use IntegraCommerce\Api\Handler\Response\HandlerInterfaceSuccess;

interface TypeResponseInterface extends TypeInterface
{
    /**
     * @param string $status
     *
     * @return $this
     */
    public function setStatusCode($status = null);

    /**
     * @param HandlerInterfaceSuccess $handler
     *
     * @return $this
     */
    public function importResponseHandler(HandlerInterfaceSuccess $handler);

    /**
     * @param HandlerInterfaceException $handler
     *
     * @return $this
     */
    public function importResponseExceptionHandler(HandlerInterfaceException $handler);
}
