<?php
/**
 * B2W Digital - Companhia Digital
 *
 * Do not edit this file if you want to update this SDK for future new versions.
 * For support please contact the e-mail bellow:
 *
 * sdk@e-smart.com.br
 *
 * @category  SkuHub
 * @package   SkuHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br).
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

namespace IntegraCommerce\Api\Handler\Request\Sync;

use IntegraCommerce\Api\Handler\Request\HandlerAbstract;

class ErrorsHandler extends HandlerAbstract
{

    /** @var string */
    protected $baseUrlPath = '/sync_errors';


    /**
     * @return \IntegraCommerce\Api\Handler\Response\HandlerInterface
     */
    public function categoriesErrors()
    {
        /** @var \IntegraCommerce\Api\Handler\Response\HandlerInterface $responseHandler */
        $responseHandler = $this->service()->get($this->baseUrlPath('Category'));
        return $responseHandler;
    }


    /**
     * @param string $categoryCode
     *
     * @return \IntegraCommerce\Api\Handler\Response\HandlerInterface
     */
    public function categoryErrors($categoryCode)
    {
        /** @var \IntegraCommerce\Api\Handler\Response\HandlerInterface $responseHandler */
        $responseHandler = $this->service()->get($this->baseUrlPath("Category/{$categoryCode}"));
        return $responseHandler;
    }


    /**
     * @return \IntegraCommerce\Api\Handler\Response\HandlerInterface
     */
    public function productsErrors()
    {
        /** @var \IntegraCommerce\Api\Handler\Response\HandlerInterface $responseHandler */
        $responseHandler = $this->service()->get($this->baseUrlPath('Product'));
        return $responseHandler;
    }


    /**
     * @return \IntegraCommerce\Api\Handler\Response\HandlerInterface
     */
    public function ordersErrors()
    {
        /** @var \IntegraCommerce\Api\Handler\Response\HandlerInterface $responseHandler */
        $responseHandler = $this->service()->get($this->baseUrlPath('Order'));
        return $responseHandler;
    }


    /**
     * @todo It needs to be wrapped up.
     *
     * @var array $errors
     *
     * @return \IntegraCommerce\Api\Handler\Response\HandlerInterface
     */
    public function ignoreProductErrors(
        array $errors = [
            ['entity_id' => null, 'error_category_code' => null, 'error_code' => null]
        ]
    ) {
        /** @var \IntegraCommerce\Api\Handler\Response\HandlerInterface $responseHandler */
        $responseHandler = $this->service()->patch($this->baseUrlPath('Product'), [
            'errors' => $errors
        ]);
        return $responseHandler;
    }


    /**
     * @todo It needs to be wrapped up.
     *
     * @var array $errors
     *
     * @return \IntegraCommerce\Api\Handler\Response\HandlerInterface
     */
    public function ignoreOrderErrors(
        array $errors = [
            ['entity_id' => null, 'error_category_code' => null, 'error_code' => null]
        ]
    ) {
        /** @var \IntegraCommerce\Api\Handler\Response\HandlerInterface $responseHandler */
        $responseHandler = $this->service()->patch($this->baseUrlPath('orders'), [
            'errors' => $errors
        ]);
        return $responseHandler;
    }


    /**
     * @return null
     */
    public function entityInterface()
    {
        return null;
    }
}
