<?php
/**
 * B2W Digital - Companhia Digital
 *
 * Do not edit this file if you want to update this SDK for future new versions.
 * For support please contact the e-mail bellow:
 *
 * sdk@e-smart.com.br
 *
 * @category  SkuHub
 * @package   SkuHub
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br).
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 */

namespace IntegraCommerce\Api\Handler\Request\Catalog;

use IntegraCommerce\Api\EntityInterface\Catalog\Category;
use IntegraCommerce\Api\Handler\Request\HandlerAbstract;
use IntegraCommerce\Api\DataTransformer\Catalog\Category\Create as CreateTransformer;
use IntegraCommerce\Api\DataTransformer\Catalog\Category\Update as UpdateTransformer;

class CategoryHandler extends HandlerAbstract
{

    /** @var string */
    protected $baseUrlPath = '/Category';


    /**
     * @return \IntegraCommerce\Api\Handler\Response\HandlerInterface
     */
    public function categories()
    {
        /** @var \IntegraCommerce\Api\Handler\Response\HandlerInterface $responseHandler */
        $responseHandler = $this->service()->get($this->baseUrlPath());
        return $responseHandler;
    }


    /**
     * @param string $code
     * @param string $name
     *
     * @return \IntegraCommerce\Api\Handler\Response\HandlerInterface
     */
    public function create($code, $name)
    {
        $transformer = new CreateTransformer($code, $name);
        $body        = $transformer->output();

        /** @var \IntegraCommerce\Api\Handler\Response\HandlerInterface $responseHandler */
        $responseHandler = $this->service()->post($this->baseUrlPath(), $body);

        return $responseHandler;
    }


    /**
     * @param string $code
     * @param string $name
     *
     * @return \IntegraCommerce\Api\Handler\Response\HandlerInterface
     */
    public function update($code, $name)
    {
        $transformer = new UpdateTransformer($code, $name);
        $body        = $transformer->output();

        /** @var \IntegraCommerce\Api\Handler\Response\HandlerInterface $responseHandler */
        $responseHandler = $this->service()->put($this->baseUrlPath($code), $body);

        return $responseHandler;
    }


    /**
     * @param string $code
     *
     * @return \IntegraCommerce\Api\Handler\Response\HandlerInterface
     */
    public function delete($code)
    {
        /** @var \IntegraCommerce\Api\Handler\Response\HandlerInterface $responseHandler */
        $responseHandler = $this->service()->delete($this->baseUrlPath($code));
        return $responseHandler;
    }


    /**
     * @return Category|\IntegraCommerce\Api\EntityInterface\Catalog\Category
     */
    public function entityInterface()
    {
        return new Category($this);
    }
}
