<?php
/**
 * B2W Digital - Companhia Digital
 *
 * Do not edit this file if you want to update this SDK for future new versions.
 * For support please contact the e-mail bellow:
 *
 * sdk@e-smart.com.br
 *
 * @category  IntegraCommerce
 * @package   IntegraCommerce
 *
 * @copyright Copyright (c) 2018 B2W Digital - BSeller Platform. (http://www.bseller.com.br).
 *
 * @author    Tiago Sampaio <tiago.sampaio@e-smart.com.br>
 * @author    Bruno Gemelli <bruno.gemelli@e-smart.com.br>
 */

namespace IntegraCommerce;

use IntegraCommerce\Api\Handler\Request\Getters as RequestHandlerGetters;
use IntegraCommerce\Api\EntityInterface\Getters as EntityInterfaceGetters;
use IntegraCommerce\Api\Service\ServiceAbstract;
use IntegraCommerce\Api\Service\ServiceInterface;
use IntegraCommerce\Api\Service\ServiceJson;

class Api implements ApiInterface
{
    use RequestHandlerGetters, EntityInterfaceGetters;

    /**
     * @var string
     */
    //const HEADER_USER_EMAIL = 'X-User-Email';
    const HEADER_USER_EMAIL = "Authorization";

    /**
     * @var string
     */
    //const HEADER_API_KEY = 'X-Api-Key';
    const HEADER_API_KEY = "Content-Type";

    /**
     * @var string
     */
    //const HEADER_ACCOUNT_MANAGER_KEY = 'X-Accountmanager-Key';
    const HEADER_ACCOUNT_MANAGER_KEY = "Content-Type";

    /**
     * @var ServiceAbstract
     */
    private $service = null;

    /**
     * @inheritdoc
     */
    public function __construct(
        string $email,
        string $apiKey,
        string $xAccountKey = null,
        string $baseUri = null,
        ServiceInterface $apiService = null
    ) {
        /**
         * If you need support in the future from IntegraCommerce please don't change this code.
         */
        if (empty($xAccountKey)) {
            $xAccountKey = '!d1Z!iQGddENHAtcP6vc';
        }

        // $headers = [
        //     self::HEADER_USER_EMAIL          => $email,
        //     self::HEADER_API_KEY             => $apiKey,
        //     self::HEADER_ACCOUNT_MANAGER_KEY => $xAccountKey,
        // ];

        $headers = [
            self::HEADER_USER_EMAIL          => "Basic ". base64_encode("$email:$apiKey"),
            self::HEADER_API_KEY             =>"application/json",
            self::HEADER_ACCOUNT_MANAGER_KEY => "application/json",
        ];

        // $headers = [
        //     "Authorization" => "Basic ". base64_encode("$email:$apiKey") ,
        //     "Content-Type"=> "application/json"// <---
        // ];

        $this->initService($baseUri, $apiService);
        $this->initHeaders($headers);
    }

    /**
     * Reset the authorization information and use the same instance of the API object to use different accounts.
     *
     * @param string $email
     * @param string $apiKey
     *
     * @return $this
     */
    public function setAuthentication($email, $apiKey)
    {
        // $headers = [
        //     self::HEADER_USER_EMAIL => $email,
        //     self::HEADER_API_KEY    => $apiKey,
        // ];
        $headers = [
            "Authorization" => "Basic ". base64_encode("$email:$apiKey") ,
            "Content-Type"=> "application/json"// <---
        ];

        $this->initHeaders($headers);

        return $this;
    }

    /**
     * Gets a single connection instance.
     *
     * @return ServiceAbstract
     */
    public function service()
    {
        return $this->service;
    }

    /**
     * @param array $headers
     *
     * @return $this
     */
    private function initHeaders(array $headers = [])
    {
        $this->service()->getOptionsBuilder()
            ->getHeadersBuilder()
            ->addHeaders($headers);

        return $this;
    }

    /**
     * @param null                  $baseUri
     * @param ServiceInterface|null $apiService
     *
     * @return $this
     */
    private function initService($baseUri = null, ServiceInterface $apiService = null)
    {
        if (empty($apiService)) {
            $apiService = new ServiceJson($baseUri);
        }

        $this->service = $apiService;

        return $this;
    }
}
